# Generated by Django 5.2.8 on 2026-04-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Отредактировано'),
        ),
    ]
