# Generated by Django 5.2.8 on 2026-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_newscomment_is_edited_newscomment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomment',
            name='sentiment_analyzed',
            field=models.BooleanField(default=False, verbose_name='Проанализирован'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тональность'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sentiment_analyzed',
            field=models.BooleanField(default=False, verbose_name='Проанализирован'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Тональность'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность'),
        ),
    ]
